import type { Palette } from "./palette"

interface SyntaxToken {
  color: string
  font_style: string | null
  font_weight: number | null
}

export interface ZedTheme {
  name: string
  appearance: "dark" | "light"
  style: Record<string, unknown>
}

export function buildZedTheme(
  name: string,
  appearance: "dark" | "light",
  p: Palette
): ZedTheme {
  const activeLine = appearance === "dark" ? "#ffffff0d" : "#00000008"

  const token = (
    color: string,
    font_style: string | null = null,
    font_weight: number | null = null
  ): SyntaxToken => ({ color, font_style, font_weight })

  return {
    name,
    appearance,
    style: {
      "border":                                     p.border,
      "border.variant":                             p.fg_muted,
      "border.focused":                             p.fn,
      "border.selected":                            p.keyword,
      "border.transparent":                         null,
      "border.disabled":                            p.fg_muted,
      "elevated_surface.background":                p.bg_elevated,
      "surface.background":                         p.bg_surface,
      "background":                                 p.bg,
      "element.background":                         p.bg_surface,
      "element.hover":                              p.bg_surface + "99",
      "element.active":                             p.keyword + "33",
      "element.selected":                           p.bg + "99",
      "element.disabled":                           p.fg_muted,
      "drop_target.background":                     p.bg_surface,
      "ghost_element.background":                   null,
      "ghost_element.hover":                        p.bg + "99",
      "ghost_element.active":                       p.fg_muted + "80",
      "ghost_element.selected":                     p.fg_muted + "99",
      "ghost_element.disabled":                     p.fg_muted,
      "text":                                       p.fg,
      "text.muted":                                 p.fg_muted,
      "text.placeholder":                           p.fg_muted,
      "text.disabled":                              p.fg_muted,
      "text.accent":                                p.fn,
      "icon":                                       p.fg,
      "icon.muted":                                 p.fg_muted,
      "icon.disabled":                              p.fg_muted,
      "icon.placeholder":                           p.fg_muted,
      "icon.accent":                                p.fn,
      "status_bar.background":                      p.bg_elevated,
      "title_bar.background":                       p.bg_elevated,
      "toolbar.background":                         p.bg,
      "tab_bar.background":                         p.bg,
      "tab.inactive_background":                    p.bg,
      "tab.active_background":                      p.bg_surface,
      "search.match_background":                    p.type + "33",
      "panel.background":                           p.bg_elevated,
      "panel.focused_border":                       p.fg,
      "pane.focused_border":                        p.fg,
      "scrollbar.thumb.background":                 p.fg_muted + "50",
      "scrollbar.thumb.hover_background":           p.fg_muted,
      "scrollbar.thumb.border":                     p.fg_muted + "50",
      "scrollbar.track.background":                 p.bg,
      "scrollbar.track.border":                     p.border,
      "editor.foreground":                          p.fg,
      "editor.background":                          p.bg,
      "editor.gutter.background":                   p.bg,
      "editor.subheader.background":                p.bg_surface,
      "editor.active_line.background":              activeLine,
      "editor.highlighted_line.background":         null,
      "editor.line_number":                         p.line_number,
      "editor.active_line_number":                  p.fg_muted,
      "editor.invisible":                           p.fg_muted,
      "editor.wrap_guide":                          p.border,
      "editor.active_wrap_guide":                   p.border,
      "editor.document_highlight.read_background":  p.fg_muted + "29",
      "editor.document_highlight.write_background": p.fg_muted + "29",
      "terminal.background":                        p.bg_elevated,
      "terminal.foreground":                        p.fg,
      "terminal.bright_foreground":                 null,
      "terminal.dim_foreground":                    null,
      "terminal.ansi.black":                        p.bg_surface,
      "terminal.ansi.bright_black":                 p.fg_muted,
      "terminal.ansi.dim_black":                    null,
      "terminal.ansi.red":                          p.tag,
      "terminal.ansi.bright_red":                   p.tag,
      "terminal.ansi.dim_red":                      null,
      "terminal.ansi.green":                        p.comment,
      "terminal.ansi.bright_green":                 p.comment,
      "terminal.ansi.dim_green":                    null,
      "terminal.ansi.yellow":                       p.parameter,
      "terminal.ansi.bright_yellow":                p.parameter,
      "terminal.ansi.dim_yellow":                   null,
      "terminal.ansi.blue":                         p.fn,
      "terminal.ansi.bright_blue":                  p.fn,
      "terminal.ansi.dim_blue":                     null,
      "terminal.ansi.magenta":                      p.keyword,
      "terminal.ansi.bright_magenta":               p.keyword,
      "terminal.ansi.dim_magenta":                  null,
      "terminal.ansi.cyan":                         p.operator,
      "terminal.ansi.bright_cyan":                  p.operator,
      "terminal.ansi.dim_cyan":                     null,
      "terminal.ansi.white":                        p.fg,
      "terminal.ansi.bright_white":                 p.fg,
      "terminal.ansi.dim_white":                    null,
      "link_text.hover":                            p.type,
      "conflict":                                   p.keyword,
      "conflict.border":                            p.keyword,
      "conflict.background":                        p.bg_surface,
      "created":                                    p.type,
      "created.border":                             p.type,
      "created.background":                         p.bg_surface,
      "deleted":                                    p.tag,
      "deleted.border":                             p.tag,
      "deleted.background":                         p.bg_surface,
      "error":                                      p.tag,
      "error.border":                               p.tag,
      "error.background":                           p.bg_surface,
      "hidden":                                     p.fg_muted,
      "hidden.border":                              p.fg_muted,
      "hidden.background":                          p.bg_surface,
      "hint":                                       p.parameter,
      "hint.border":                                p.parameter,
      "hint.background":                            p.bg_surface,
      "ignored":                                    p.fg_muted,
      "ignored.border":                             p.fg_muted,
      "ignored.background":                         p.bg_surface,
      "info":                                       p.type,
      "info.border":                                p.type,
      "info.background":                            p.fn + "33",
      "modified":                                   p.parameter,
      "modified.border":                            p.parameter,
      "modified.background":                        p.bg_surface,
      "predictive":                                 p.fg_muted,
      "predictive.border":                          p.fg_muted,
      "predictive.background":                      p.bg_surface,
      "renamed":                                    p.operator,
      "renamed.border":                             p.operator,
      "renamed.background":                         p.bg_surface,
      "success":                                    p.type,
      "success.border":                             p.type,
      "success.background":                         p.bg_surface,
      "unreachable":                                p.tag,
      "unreachable.border":                         p.tag,
      "unreachable.background":                     p.bg_surface,
      "warning":                                    p.string,
      "warning.border":                             p.string,
      "warning.background":                         p.bg_surface,
      "players": [
        { cursor: "#f5e0dc", selection: "#f5e0dc66", background: "#f5e0dc" },
        { cursor: p.keyword, selection: p.keyword + "66", background: p.keyword },
        { cursor: p.type,    selection: p.type + "66",    background: p.type    },
        { cursor: p.fn,      selection: p.fn + "66",      background: p.fn      },
      ],
      "syntax": {
        "attribute":               token(p.number),
        "boolean":                 token(p.number),
        "comment":                 token(p.comment, "italic"),
        "comment.doc":             token(p.comment, "italic"),
        "constant":                token(p.number),
        "constructor":             token(p.fn),
        "embedded":                token(p.tag),
        "emphasis":                token(p.tag, "italic"),
        "emphasis.strong":         token(p.tag, null, 700),
        "enum":                    token(p.type),
        "float":                   token(p.number),
        "function":                token(p.fn, "italic"),
        "function.call":           token(p.fg),
        "function.method":         token(p.fn, "italic"),
        "hint":                    token(p.type, "italic"),
        "include":                 token(p.keyword),
        "keyword":                 token(p.keyword),
        "keyword.operator":        token(p.keyword),
        "link_text":               token(p.fn),
        "link_uri":                token(p.fn),
        "method":                  token(p.fn),
        "method.call":             token(p.fg),
        "number":                  token(p.number),
        "operator":                token(p.operator),
        "parameter":               token(p.parameter),
        "predoc":                  token(p.tag),
        "predictive":              token(p.fg_muted),
        "primary":                 token(p.fg),
        "property":                token(p.property),
        "punctuation":             token(p.operator),
        "punctuation.bracket":     token(p.fn),
        "punctuation.delimiter":   token(p.fg_muted),
        "punctuation.list_marker": token(p.operator),
        "punctuation.special":     token(p.operator),
        "punctuation.special.symbol": token(p.tag),
        "repeat":                  token(p.keyword),
        "string":                  token(p.string),
        "string.escape":           token(p.string_escape),
        "string.regex":            token(p.string_escape),
        "string.special":          token(p.keyword),
        "string.special.symbol":   token(p.tag),
        "tag":                     token(p.tag),
        "text.literal":            token(p.type),
        "title":                   token(p.fg, null, 800),
        "type":                    token(p.type),
        "type.qualifier":          token(p.keyword),
        "variable":                token(p.fg),
        "variable.special":        token(p.parameter),
        "variant":                 token(p.tag),
      },
    },
  }
}
